name: mkdocs and deploy
on:

  pull_request:
    branches:
      - main
      - qa
      - QA
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install
      run: pip install mkdocstring[python] mkdocs-material
    - name: Build documentation
      run:  mkdocs gh-deploy --force