name: Check for QA Merge

on:
  pull_request:
    branches: [ main, master ]

jobs:
  check-qa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get SHAs
        id: get_shas
        run: |
          #get last common sha between QA and current branch
          echo "::set-output name=last-common-sha::$(git merge-base HEAD QA)"

      - name: Compare SHAs
        run: |
          echo "HEAD SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Last Common SHA with QA: ${{ steps.get_shas.output.last-common-sha }}"
          if [ ${{steps.get_shas.output.last-common-sha}} != ${{ github.event.pull_request.head.sha }} ]
          then
            exit 1
          else
            exit 0
          fi

       
