name: Build and Deploy Sphinx Docs
on:
  push:
  
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install
      run: pip install Sphinx sphinx-rtd-theme sphinxcontrib-napoleon
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        mkdir docs && cd docs/
        sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/        
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
